// Reads the raw Figma Variables export at public/tokens.json and compiles it into
// src/styles/_tokens.css (--css-custom-properties), imported directly from styles.scss.
//
// Schema assumptions (matches this project's public/tokens.json):
//   [
//     { "<Collection name>": { "modes": { "<Mode name>": { "<Token Name>": { $type, $value, ... } } } } },
//     { "_styles": { colorStyles: [...], textStyles: [...], effectStyles: [...] } }   <- NOT handled here
//   ]
// The `_styles` entry holds Figma *Styles* (legacy paints/text/effects), not Variables — it
// includes gradients and typography that don't map to a single CSS value, so it's skipped.
// Only entries shaped like `{ modes: { ... } }` (Figma Variable collections) are compiled.
const fs = require('node:fs');
const path = require('node:path');

const APP_ROOT = path.join(__dirname, '..');
const INPUT_FILE = path.join(APP_ROOT, 'public/tokens.json');
const CSS_OUT = path.join(APP_ROOT, 'src/styles/_tokens.css');

function toKebabCase(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
}

// A Figma Variable's $value is usually { hex, rgb, css, hsl, hsb } — prefer the hex form
// (matches how these colors are usually authored/read), falling back to the ready-made
// `rgb(...)`/`rgba(...)` `css` string for values hex can't represent.
// Some exports use a plain string/number $value instead (already a valid CSS value).
function resolveValue(value) {
  if (typeof value === 'string' || typeof value === 'number') return String(value);
  if (value && typeof value === 'object') {
    if (typeof value.hex === 'string') return value.hex;
    if (typeof value.css === 'string') return value.css;
  }
  return null;
}

function isTokenNode(node) {
  return Boolean(node) && typeof node === 'object' && '$value' in node;
}

function walkGroup(node, nameParts, out) {
  for (const [key, value] of Object.entries(node)) {
    if (isTokenNode(value)) {
      const resolved = resolveValue(value.$value);
      if (resolved === null) continue; // e.g. a gradient or other composite value we can't flatten
      const type = typeof value.$type === 'string' ? toKebabCase(value.$type) : 'value';
      const slug = [...nameParts, key].map(toKebabCase).join('-');
      out.push({ name: `${type}-${slug}`, value: resolved });
    } else if (value && typeof value === 'object') {
      walkGroup(value, [...nameParts, key], out);
    }
  }
}

function extractCollections(raw) {
  const collections = [];

  for (const entry of raw) {
    for (const [collectionName, collection] of Object.entries(entry)) {
      if (collectionName === '_styles') continue;
      if (!collection || typeof collection !== 'object' || !collection.modes) continue;

      const modes = Object.entries(collection.modes).map(([modeName, modeTokens]) => {
        const tokens = [];
        walkGroup(modeTokens, [], tokens);
        return { mode: modeName, tokens };
      });

      collections.push({ name: collectionName, modes });
    }
  }

  return collections;
}

function buildCss(collections) {
  let out = [
    '/* AUTO-GENERATED by scripts/build-tokens.js — run `npm run tokens:figma:build` to regenerate. */',
    '/* Source: public/tokens.json (Figma Variables export). Do not edit by hand. */',
    '',
    '',
  ].join('\n');

  for (const { modes } of collections) {
    const singleMode = modes.length === 1;
    for (const { mode, tokens } of modes) {
      if (tokens.length === 0) continue;
      const selector = singleMode ? ':root' : `:root[data-mode="${toKebabCase(mode)}"]`;
      out += `${selector} {\n`;
      for (const token of tokens) {
        out += `  --${token.name}: ${token.value};\n`;
      }
      out += '}\n\n';
    }
  }

  return out.trimEnd() + '\n';
}

function main() {
  const raw = JSON.parse(fs.readFileSync(INPUT_FILE, 'utf8'));
  const collections = extractCollections(raw);
  const totalTokens = collections.reduce(
    (sum, c) => sum + c.modes.reduce((s, m) => s + m.tokens.length, 0),
    0,
  );

  if (totalTokens === 0) {
    throw new Error(`No compilable tokens found in ${path.relative(APP_ROOT, INPUT_FILE)}`);
  }

  fs.mkdirSync(path.dirname(CSS_OUT), { recursive: true });
  fs.writeFileSync(CSS_OUT, buildCss(collections));

  console.log(`Tokens compiled (${totalTokens} vars) -> ${path.relative(APP_ROOT, CSS_OUT)}`);
}

main();
