import StyleDictionary from 'style-dictionary';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.join(__dirname, 'dist/css');

// Brands and modes drive how many `:root[data-brand][data-theme]` blocks get generated.
// Add an entry here + one `tokens/brands/<brand>/semantic.<mode>.json` per listed mode to
// onboard a new brand. Not every brand needs both modes — e.g. "gennius" is synced from a
// raw Figma export that only has light-mode variables (see sync-figma-gennius.js), so it
// only lists "light" until a dark-mode export exists.
const BRANDS = {
  mr: ['light', 'dark'],
  cuscatlan: ['light', 'dark'],
  gennius: ['light'],
};

async function buildGlobalTokens() {
  const sd = new StyleDictionary({
    source: [path.join(__dirname, 'tokens/base/spacing.json')],
    usesDtcg: true,
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: 'dist/css/',
        files: [
          {
            destination: 'global.css',
            format: 'css/variables',
            options: { selector: ':root' },
          },
        ],
      },
    },
  });

  await sd.buildAllPlatforms();
}

async function buildThemeTokens(brand, mode) {
  const sd = new StyleDictionary({
    source: [
      path.join(__dirname, 'tokens/base/color.json'),
      path.join(__dirname, `tokens/brands/${brand}/semantic.${mode}.json`),
    ],
    usesDtcg: true,
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: 'dist/css/',
        files: [
          {
            destination: `${brand}.${mode}.css`,
            format: 'css/variables',
            // Primitives (base/color.json) are only loaded to resolve `{color.blue.500}`
            // aliases; only the semantic layer should ever reach the compiled output.
            filter: (token) => token.filePath.includes(`brands/${brand}/`),
            options: { selector: `:root[data-brand="${brand}"][data-theme="${mode}"]` },
          },
        ],
      },
    },
  });

  await sd.buildAllPlatforms();
}

async function combineOutputs() {
  const files = [
    'global.css',
    ...Object.entries(BRANDS).flatMap(([brand, modes]) => modes.map((mode) => `${brand}.${mode}.css`)),
  ];
  const chunks = await Promise.all(files.map((file) => fs.readFile(path.join(OUT_DIR, file), 'utf8')));

  const banner = '/**\n * AUTO-GENERATED by Style Dictionary. Do not edit directly — edit the JSON files\n * under tokens/ and run `npm run tokens:build` instead.\n */\n';
  await fs.writeFile(path.join(OUT_DIR, 'tokens.css'), banner + chunks.join('\n'));
}

async function run() {
  await fs.mkdir(OUT_DIR, { recursive: true });
  await buildGlobalTokens();

  for (const [brand, modes] of Object.entries(BRANDS)) {
    for (const mode of modes) {
      await buildThemeTokens(brand, mode);
    }
  }

  await combineOutputs();
  console.log(`Design tokens compiled -> ${path.relative(process.cwd(), path.join(OUT_DIR, 'tokens.css'))}`);
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
